### ISSUE TITLE
Status is always "error"

### ISSUE THREAD

**Issue by Alucard616** [theforeman/foreman_expire_hosts#1]
Every host gets an Expiration Status warning and sets the general status to error. It doens't matter if the expiration date is in two days or in one year.
(of cource only when i set an expiration date first)

**Comment by timogoebel** [comment]
@Alucard616 : Thank you for the report. Do you still see this issue with a recent version of the plugin?

**Comment by Alucard616** [comment]
@timogoebel thanks at first for making this plugin compatible with foreman 1.13

The good news is, that I don't get this issue now.
The bad news is, that i don't have a status for the expiration date at all.
I can set it in "Additional Information" as before, but unfortunately it isn't saved.
It doesn't matter if i want to set it afterwards or if i set when creating a new host.

**Comment by timogoebel** [comment]
@Alucard616: Thanks for trying. I did notice the issue myself last night and just released 2.1.1 which fixes the problem. I submitted it for packaging just now. Once it is in the repos, can you give it a shot? As a workaround you should be able to set this in the "Host List". Just select the host via the checkbox and change the expiration date as you would for multiple hosts.

**Comment by Alucard616** [comment]
@timogoebel the workaround works perfectly fine.
I'll contact you, when I installed the Update

**Comment by Alucard616** [comment]
@timogoebel still waiting for the package in the repo :)

**Comment by timogoebel** [comment]
@Alucard616 : Thanks for letting me know, the 2.1.1 package is in the repo now.

**Comment by Alucard616** [comment]
@timogoebel Thank you very much :)
It appears, that it works now :)

But with the new Update I often get this error, when I click on new host:

> Oops, we're sorry but something went wrong Missing partial /hosts/_expired_on_field with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :rabl]}. Searched in: \* "/usr/share/foreman/app/views" \* "/opt/theforeman/tfm/root/usr/share/gems/gems/foreman_expire_hosts-2.1.0/app/views" \* "/opt/theforeman/tfm/root/usr/share/gems/gems/foreman_abrt-0.0.7/app/views" \* "/opt/theforeman/tfm/root/usr/share/gems/gems/foreman_cockpit-2.0.2/app/views" \* "/opt/theforeman/tfm/root/usr/share/gems/gems/foreman_remote_execution-1.2.1/app/views" \* "/opt/theforeman/tfm/root/usr/share/gems/gems/foreman-tasks-0.8.2/app/views" \* "/opt/theforeman/tfm/root/usr/share/gems/gems/foreman_setup-5.0.0/app/views" \* "/opt/theforeman/tfm/root/usr/share/gems/gems/apipie-rails-0.3.6/app/views"

This Problem is new. I had installed the other Plugins before and it worked perfectly fine :)

**Comment by timogoebel** [comment]
@Alucard616 : Thanks, I'll take a look. Can't promise that I'll find time today, though.

**Comment by Alucard616** [comment]
@timogoebel no problem :)

**Comment by dgoetz** [comment]
I see this problem still existing with Foreman 1.13.2 and Plugin version 2.1.1 (everything freshly installed). Setting a host to expire in one year gives it a warning banner, global status warning and Expiration Status "Pending expiration on 2017-12-13".

**Comment by timogoebel** [comment]
@dgoetz : Thanks for the report. I'll look into this next week when I'm back in the office.

**Comment by timogoebel** [comment]
I have opened #4, that should fix this issue.
