### ISSUE TITLE
Expired Host Menu Option No Longer Appears On Hosts Index

### ISSUE THREAD

**Issue by ssmiller25** [theforeman/foreman_expire_hosts#19]
On the Host Index, there is no longer an option to bulk update expiration dates.  It appears to be broken functionality in app/overrides/add_js_to_host_index.rb , which I can only presume is related to the move to React on the UI

**Comment by timogoebel** [comment]
@ssmiller25: What Foreman + Plugin version are you running?

**Comment by ssmiller25** [comment]
@timogoebel Sorry about that!  Foreman 1.16.0 and expire_hosts 4.0.0

**Comment by timogoebel** [comment]
@ssmiller25: #20 should address this issue. Thanks for letting us know.

**Comment by ssmiller25** [comment]
Finally got around to attempting to test.  In 1.16 is breaks pretty badly, but I assume because it's still on Rails 4.2.  I'll try to deploy a dev enviornment and test it there if I get a chance.

Thanks!
