### ISSUE TITLE
Settings tab not shown in Foreman 1.18

### ISSUE THREAD

**Issue by dgoetz** [theforeman/foreman_expire_hosts#27]
The settings tab is not shown in Foreman 1.18, but the log is showing no failure.
Only thing relevant to expire hosts is `Deface: [WARNING] No :original defined for 'host_form_expired_on_field', you should change its definition to include:`

**Comment by timogoebel** [comment]
@dgoetz: Thanks for the bug report. I'm not sure what you think is missing:

The host form is correctly enhanced:

![image](https://user-images.githubusercontent.com/4107560/42374856-e8f6af82-8119-11e8-8e64-dd2d6dd4ddc1.png)

I can also see the tab `Expire Hosts` in Settings (at least in my devel environment).

![image](https://user-images.githubusercontent.com/4107560/42374911-17e17d54-811a-11e8-95c6-1ffd87aea249.png)

**Comment by dgoetz** [comment]
I am missing the settings tab in 1.18.0-RC3. Can this be a collision with another plugin?

![grafik](https://user-images.githubusercontent.com/3658213/42375867-4991f056-811d-11e8-9441-85df2dc230d7.png)
![grafik](https://user-images.githubusercontent.com/3658213/42375879-5b0cab1e-811d-11e8-9b40-d18ffaacfbad.png)

**Comment by dgoetz** [comment]
It has to be a collision or caused by the number of installed plugin, because the same has now also happened with the Monitoring plugin. It is showing up as installed, in the host edit form I can set the Monitoring Smart Proxy, but no Settings tab.

**Comment by timogoebel** [comment]
That's weird. Do the settings show up in the database (settings table)? The `category` should be `Settings::ExpireHosts` or `Settings::Monitoring`.

**Comment by dgoetz** [comment]
No database entries are there for `Settings::ExpireHosts` or `Setting::ExpireHosts` (or Monitoring).

**Comment by timogoebel** [comment]
That's odd, they should be loaded during app startup.

**Comment by dgoetz** [comment]
Seems to be gone in current releases.
