### ISSUE TITLE
Update not available in repo

### ISSUE THREAD

**Issue by Alucard616** [theforeman/foreman_expire_hosts#5]
Hi!

Did you updated the Repository, too? I can not receive the Package until now.

**Comment by timogoebel** [comment]
@Alucard616: I have not released a new version, yet. Hang tight.

**Comment by timogoebel** [comment]
@Alucard616 : I have submitted a new release to rubygems. Packaging is in review right now: https://github.com/theforeman/foreman-packaging/pull/1460

**Comment by Alucard616** [comment]
@timogoebel aah thanks for your quick response :)

**Comment by Alucard616** [comment]
@timogoebel got the Update. This issue can be closed
