### ISSUE TITLE
No possibility to set permissions

### ISSUE THREAD

**Issue by Alucard616** [theforeman/foreman_expire_hosts#6]
Since Foreman 1.13 you can set permissions for everything and filter them.
To use your Plugin I have to be Administrator, otherwise I do not have the permissions even when I'm allowed to do everything else e.g. deleting a host.
Is there any possibility to add this?

**Comment by timogoebel** [comment]
@Alucard616 : What do you want to do exactly that required admin permissions?

**Comment by Alucard616** [comment]
@timogoebel in "Additional Information" when editing/creating a host the "Expired on" field.
I can only add a value, when I am Administrator

**Comment by timogoebel** [comment]
@Alucard616 : Is the input field disabled or does it give you an error when you save the host?

**Comment by Alucard616** [comment]
@timogoebel the calendar doesn't appear and when I type a date in that field I get an error, that I do not have any permissions to do this

**Comment by timogoebel** [comment]
@Alucard616 : Thanks for reporting this, I'll look into it. Currently the plugin only supports editing the expiration date for the owner of a host. I think, it's reasonable to add a dedicated permission for this.

**Comment by timogoebel** [comment]
@Alucard616 : I've created #7 that should address this issue.
